# Generated by Django 2.1.7 on 2020-07-14 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('andalous', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='happy_costumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', tinymce.models.HTMLField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('coctumer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('costumer_pic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='andalous.author')),
            ],
        ),
    ]
